### ISSUE TITLE
Posts: the feed and `published: false`

### ISSUE THREAD

**Issue by larsgw** [cdli-gh/blog#2]
I have two matters of discussion about the technical setup of weekly posts, but they are so intertwined I'm making a single issue.

  1. I was planning on adding `published: false` to the yet unwritten weekly updates in my part of the blog. From what I understand, that hides all the boilerplate text until I write the post and decide to publish it. Another benefit could be that posts probably won't show up on the Atom feed until they are written/published.

  2. However, the feed doesn't seem to work. From what I can tell, we're making Pages and not Posts, and [`jekyll-feed` only supports the latter](https://github.com/jekyll/jekyll-feed/issues/217#issuecomment-378570219). Unless there is a way to make the collections counts as Posts, we would need to change the directory structure quite a bit, or fork and patch `jekyll-feed`.

**Comment by thesagarsehgal** [comment]
HI @larsgw !  Yes, you are right that we are using pages instead of posts here.  There was no such requirement of hiding the page and thus wasn't under consideration. 
Give me some time and that feature would be up. 

As per my knowledge, there won't be much of effort to hide a post, and no directory structure would need to be updated. ( I hope so :) )

**Comment by thesagarsehgal** [comment]
Okay, so here it is. Just add a tag of `draft` and it won't be listed on your page. Even though you can access them using the URL.

Like this:-
```
tags: ["draft","week","gsoc","gsoc2020","api","eval#1","week#1"]
```

I have added a draft page in your folder named `draft.md`. Have a look at it.

**Comment by epageperron** [comment]
@larsgw

**Comment by larsgw** [comment]
I added the draft tags to my posts, thanks. The feed I was talking about is the Atom feed at https://cdli-gh.github.io/blog/feed.xml.

**Comment by epageperron** [comment]
Ohhh. Do we need the feed ??

**Comment by thesagarsehgal** [comment]
Oh, Nice. Will surely work on it. 

@larsgw Thanks for suggesting new features :) . Keep suggesting such new features.

**Comment by thesagarsehgal** [comment]
@larsgw @epageperron I have updated the https://cdli-gh.github.io/blog/feed.xml. Now it would contain all the pages except the one with tag "draft". 

Further, unlike other RSS feeds which contain date and time it wasn't possible here since we are not mantaining the date in the blog.
